development:
  adapter: postgresql
  database: travel_development
  username: 
  password: 
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: travel_test
  username: 
  password: 
  pool: 5
  timeout: 5000

